# Generated by Django 3.0.6 on 2020-06-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_auto_20200616_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(default=''),
        ),
    ]
