# Generated by Django 3.0.6 on 2020-06-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='tracks.Comment'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='subcomment',
            field=models.TextField(blank=True),
        ),
    ]
