# Generated by Django 3.0.6 on 2020-06-24 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0013_plays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plays',
            new_name='Play',
        ),
    ]
