# Generated by Django 3.0.7 on 2020-07-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_auto_20200624_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_url',
            field=models.URLField(default='https://66.media.tumblr.com/900d93b71b6061e043a0aaa2f91a025e/fcf075c8db503555-f4/s540x810/ea7b280580ad959eac6e3d81304bc55b0d34d726.gif'),
        ),
    ]
