# Generated by Django 3.0.7 on 2020-07-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0015_userprofile_background_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playcount', to='tracks.Track')),
            ],
        ),
    ]
