# Generated by Django 3.0.6 on 2020-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='img_url',
            field=models.URLField(default='no_url'),
            preserve_default=False,
        ),
    ]
