# Generated by Django 3.0.6 on 2020-06-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.Comment'),
        ),
    ]
