# Generated by Django 3.0.6 on 2020-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20200618_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_name',
            field=models.CharField(default='Andy Tran', max_length=50),
            preserve_default=False,
        ),
    ]
