# Generated by Django 3.0.6 on 2020-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_subcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='subcomment',
            field=models.TextField(blank=True),
        ),
    ]
